# We don't use Swift internally. Disable this option.
use_frameworks!
platform: ios,"8.0"

# Use local pod code if available.
def local_pod(name, *args)
  path = File.expand_path name, '../..'

  if File.exist? path
    pod name, :path => path
  else
    pod name, *args
  end
end

# Add global dependencies here.

target 'ALAlertView_Example' do
  # If ALAlertView depends on any private pod, remember to use `local_pod`
  # to refer it explicitly.
  # CocoaPods cannot distinguish public and private pod from podspec right now,
  # it's required to do so in Podfile.
  #
  # Sample:

  # Add Example specific dependencies here...

  pod "ALAlertView", :path => "../"
end

target 'ALAlertView_Tests' do
  # Add Tests specific dependencies here...

  pod "ALAlertView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
